name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSHX VPS and capture link
        id: start_vps
        run: |
          curl -sSf https://sshx.io/get | sh -s run > output.txt
          cat output.txt
          LINK=$(grep -o 'https://sshx.io/[a-zA-Z0-9]*' output.txt | head -n 1)
          echo "SSHX_LINK=$LINK" >> $GITHUB_ENV

      - name: Send link to Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1378917239230562384/a4_I2lC5-Cv5qRFQf8VjiWqKqtHEN1gPWc4-NAfOXcPrD2KTqDGQtattjMvwhoDJj0ui
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ Your VPS is ready: $SSHX_LINK\"}" \
            $DISCORD_WEBHOOK
